// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Centralized auth session helper - always fetches a fresh session before Edge Function calls.
 * Throws AUTH_SESSION_ERROR or AUTH_SESSION_MISSING if session is invalid/missing.
 */
export async function getAuthSession() {
  const { data: { session }, error } = await supabase.auth.getSession();

  if (error) {
    console.error('Supabase getSession error:', error);
    throw new Error('AUTH_SESSION_ERROR');
  }

  if (!session?.access_token) {
    throw new Error('AUTH_SESSION_MISSING');
  }

  return session;
}